// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using internKYC;

#nullable disable

namespace internKYC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240104160159_twentythird_migration")]
    partial class twentythird_migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("internKYC.Models.ContactNumberModel", b =>
                {
                    b.Property<int>("ContactNumberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("OtpLog")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("contact_number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<string>("otp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ContactNumberId");

                    b.ToTable("ContactNumberModel");
                });

            modelBuilder.Entity("internKYC.Models.DocumentModel", b =>
                {
                    b.Property<int>("doc_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("KYCFormid")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("doc_type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("path")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("doc_id");

                    b.HasIndex("KYCFormid");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("internKYC.Models.ImageModel", b =>
                {
                    b.Property<string>("KYCForms")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Base64NICBackImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Base64NICFrontImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Base64SelfieImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("KYCForms");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("internKYC.Models.KYCFormModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ContactNumberModelId")
                        .HasColumnType("int");

                    b.Property<string>("NICNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("mobile_number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nationality")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("ContactNumberModelId")
                        .IsUnique();

                    b.ToTable("kycformdata");
                });

            modelBuilder.Entity("internKYC.Models.DocumentModel", b =>
                {
                    b.HasOne("internKYC.Models.KYCFormModel", "KYCForm")
                        .WithMany("Documents")
                        .HasForeignKey("KYCFormid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KYCForm");
                });

            modelBuilder.Entity("internKYC.Models.KYCFormModel", b =>
                {
                    b.HasOne("internKYC.Models.ContactNumberModel", "ContactNumber")
                        .WithOne("KYCForm")
                        .HasForeignKey("internKYC.Models.KYCFormModel", "ContactNumberModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactNumber");
                });

            modelBuilder.Entity("internKYC.Models.ContactNumberModel", b =>
                {
                    b.Navigation("KYCForm")
                        .IsRequired();
                });

            modelBuilder.Entity("internKYC.Models.KYCFormModel", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
